### PR TITLE
Added EEG digital Score example

### PR DESCRIPTION
**Pull request by craigvear**
Added an eeg brainwave reader -> realtime neoscore rendering in examples folder.

### CODE REVIEW

**Comment by craigvear** [comment]
Annoyingly I cannot get pre-commit to work. I have reinstalled the poetry env for Python 3.7, 3.8, 3.9 & 3.10 and get the same error (below). This is on Mac MBP (not M1) OS12.6. Pycharm 2022.2.4.

  File "/usr/local/Caskroom/miniconda/base/bin/unimport", line 10, in <module>
    sys.exit(main())
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/unimport/main.py", line 60, in main
    utils.get_used_packages(Import.imports, unused_imports)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/unimport/utils.py", line 102, in get_used_packages
    name = package_name_from_metadata(package)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/unimport/utils.py", line 90, in package_name_from_metadata
    return metadata(package)["Name"]
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 1010, in metadata
    return Distribution.from_name(distribution_name).metadata
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 567, in from_name
    raise ValueError("A distribution name is required.")
ValueError: A distribution name is required.

**Comment by craigvear** [comment]
Tried pre-commit devtools.sh and then pre-commit script on other PR. devtools installed nicely. pre_commit_hook does nothing (just returns a new line in Terminal

**Comment by ajyoon** [comment]
If the git hook doesn't actually run when you commit it's not installed properly. The script should always print some things to console, even if everything passes.

**Comment by craigvear** [comment]
works now :)

**Comment by ajyoon** [comment]
Yeah, as we discussed separately, I think this example is better kept to a separate repo because it requires external dependencies, has a separate license, and is relatively complex. Once you get it in a separate repo we can definitely highlight it here with a `external_examples.md` or similar file here and/or in the docs.

**Pull request closed without merging**
