### PR TITLE
bump img2pdf

### PR DESCRIPTION
**Pull request by jgarte**
Hi, this is more of a question than a PR. Can img2pdf be bumped to `0.4.4`? If so what would be the preferred way to do this and submit the PR (using poetry)?

### CODE REVIEW

**Comment by ajyoon** [comment]
I don't see why not - you'll just need to update the poetry lock file as well before this can be merged. I think `poetry update` should do it.

Is there a feature or patch in `0.4.4` you need? Or is this just housekeeping?

**Comment by jgarte** [comment]
> I don't see why not - you'll just need to update the poetry lock file as well before this can be merged. I think `poetry update` should do it.
> 
> Is there a feature or patch in `0.4.4` you need? Or is this just housekeeping?

Hi,

This is just housekeeping. I haven't checked yet the differences between the two versions.

**Comment by jgarte** [comment]
@ajyoon 

I ran `poetry update` and pushed a second commit for that change. Thanks for the advice.

I also tested a handful of the `examples/` to make sure everything is still working.

I'm on testing on GNU/Linux.

**Comment by ajyoon** [comment]
Thanks!

**Pull request merged**
